services:
  cashback-hub-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cashback-hub-web
    restart: always
    ports:
      - "${PORT:-8085}:80"
    environment:
      - NODE_ENV=production
