services:
  cashback-hub-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cashback-hub-server
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./server/data:/app/data
    environment:
      - PORT=4000
      - NODE_ENV=production
      - GEMINI_API_KEY=AQ.Ab8RN6KwvfUPXsMTFOkNICNX0tZo4FkhpI3h_PDtmkXKYGz9Ww

  cashback-hub-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cashback-hub-web
    restart: always
    ports:
      - "${PORT:-8085}:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - cashback-hub-server
