import { Bank } from '../types';

export const PRESET_BANKS: Bank[] = [
  {
    id: 'tbank',
    name: 'Т-Банк (Тинькофф)',
    shortName: 'Т-Банк',
    primaryColor: '#FFDD2D',
    textColor: '#1A1A1A',
    secondaryColor: '#333333',
    iconName: 'CreditCard',
    defaultMonthlyLimit: 3000,
    isActive: true,
  },
  {
    id: 'sber',
    name: 'СберБанк (СберСпасибо)',
    shortName: 'Сбер',
    primaryColor: '#21A038',
    textColor: '#FFFFFF',
    secondaryColor: '#166E26',
    iconName: 'ShieldCheck',
    defaultMonthlyLimit: 3000,
    isActive: true,
  },
  {
    id: 'alfa',
    name: 'Альфа-Банк',
    shortName: 'Альфа',
    primaryColor: '#EF3124',
    textColor: '#FFFFFF',
    secondaryColor: '#B0180E',
    iconName: 'Flame',
    defaultMonthlyLimit: 5000,
    isActive: true,
  },
  {
    id: 'vtb',
    name: 'ВТБ',
    shortName: 'ВТБ',
    primaryColor: '#002882',
    textColor: '#FFFFFF',
    secondaryColor: '#0A43C4',
    iconName: 'Building2',
    defaultMonthlyLimit: 3000,
    isActive: true,
  },
  {
    id: 'yandex',
    name: 'Яндекс Пэй',
    shortName: 'Яндекс',
    primaryColor: '#FC3F1D',
    textColor: '#FFFFFF',
    secondaryColor: '#FFCC00',
    iconName: 'Sparkles',
    defaultMonthlyLimit: 10000,
    isActive: true,
  },
  {
    id: 'ozon',
    name: 'Ozon Банк',
    shortName: 'Озон',
    primaryColor: '#005BFF',
    textColor: '#FFFFFF',
    secondaryColor: '#F01A7C',
    iconName: 'ShoppingBag',
    defaultMonthlyLimit: 3000,
    isActive: true,
  },
  {
    id: 'gpb',
    name: 'Газпромбанк',
    shortName: 'ГПБ',
    primaryColor: '#1E3A8A',
    textColor: '#FFFFFF',
    secondaryColor: '#3B82F6',
    iconName: 'Flame',
    defaultMonthlyLimit: 3000,
    isActive: false,
  },
  {
    id: 'raiffeisen',
    name: 'Райффайзенбанк',
    shortName: 'Райф',
    primaryColor: '#FFED00',
    textColor: '#000000',
    secondaryColor: '#222222',
    iconName: 'Coins',
    defaultMonthlyLimit: 5000,
    isActive: false,
  },
  {
    id: 'sovcom',
    name: 'Совкомбанк (Халва)',
    shortName: 'Совкомбанк',
    primaryColor: '#003399',
    textColor: '#FFFFFF',
    secondaryColor: '#FF3333',
    iconName: 'Smile',
    defaultMonthlyLimit: 5000,
    isActive: false,
  }
];

export const MONTH_NAMES_RU = [
  'Январь',
  'Февраль',
  'Март',
  'Апрель',
  'Май',
  'Июнь',
  'Июль',
  'Август',
  'Сентябрь',
  'Октябрь',
  'Ноябрь',
  'Декабрь'
];
